### ISSUE TITLE
Documentation for self hosting

### ISSUE THREAD

**Issue by aahnik** [remjx/coindrop#270]
How to have a page with the ui of `coindrop.to/user` in my own site `mydomain.com/donate` ?

Is there a way to write the payment methods in a config file and then general a static html file, that looks like `coindrop.to/user` that i can add to my own site ?

**Comment by remjx** [comment]
Hi @aahnik,

I do not have any immediate plans to add a self-hosted option like you describe.

You can embed an <iframe> with your Coindrop page as the `src`. The only downside to that is the pop-up button will not look as nice when you click on a payment method.
