### ISSUE TITLE
How can I know someone has paid ? How to change bitcoin or crypto address automatically ?

### ISSUE THREAD

**Issue by aahnik** [remjx/coindrop#273]
Please correct me if I am wrong.

coindrop is basically a static kind of thing, that displays all payment methods. 

Now is  there a way to know who paid how much ? I believe that is the work of a payment processor. But can coindrop be integrated with the payment processor ? 

Suppose, I lead people to my coindrop page, is there a way to collect their name , email and how much they paid via which method ?

I believe that is possible thru using API's of buymeacoffee or patreon or paypal ?

For addresses like bitcoin or upi it is not possible to verify without using a payment processor. 

Any body who has my bitcoin address can see all transanctions  for it in blockchain. So all payments I recieve will be visible. That is great for non profit organizations who want transparency. But I am planning to use coindrop page to accept payments for services. It would be great if I could generate 1000 addresses to my btc, and add upload the file to coindrop. Coindrop will display a new address whenever someone has paid to the old address.

This kind of address changing is availaible in any bitcoin wallet.

I dont know whether it is right to request these features. These will make coindrop into a complex thing. But @remjx please share your insights and thoughts about these.

thanks a ton.

**Comment by remjx** [comment]
Tracking of payment and user information is not a function of Coindrop, it is a function of whatever payment method is used.

If you want to collect user information during payment, only choose payment methods on your Coindrop page that collect that information.

If you want to generate unique blockchain addresses, I recommend using a service/wallet that handles that for you. For example, many Bitcoin SV wallets use [Paymail](https://bsvalias.org/) addresses e.g. markjackson@moneybutton.com. In this model, the sender's wallet [queries](https://bsvalias.org/04-01-basic-address-resolution.html) a unique payment address from the Paymail server. So you list a static Paymail address on Coindrop, and if somebody uses it, the address will be dynamic. 

![image](https://user-images.githubusercontent.com/35121685/107882885-cf3fc480-6eb9-11eb-87c8-4d1c163f9811.png)

**Comment by aahnik** [comment]
@remjx, thanks a lot for telling me about this. Really cool.

**Comment by aahnik** [comment]
Hi @remjx ,
Paymail is only for bsv. Is there a similar thing for other crypto ?

Does coindrop has an API ? If so, then I can easily update my crypto addresses, on certain intervals like weekly.

**Comment by remjx** [comment]
@aahnik I don't know if anything like Paymail exists for other crypto.

Coindrop does not have an API. I don't have plans to add one in the near future, sorry.

Again, I would recommend only listing payment methods that have the features you need. I find it hard to believe that there is no crypto web wallet that generates an unused BIP32 address when a potential sender visits your page.

Thanks for your questions & ideas. If you have any others let me know.
