### ISSUE TITLE
Request for MongoDB and/or PostgresSQL support

### ISSUE THREAD

**Issue by miracle091** [remjx/coindrop#335]
Like the title the possibility to support db than firebase.

Great product btw 👍

**Comment by remjx** [comment]
Thanks. Can I ask why you're asking for this? The main reason I decided to use Firebase is that it's "pay as you go".

**Comment by miracle091** [comment]
Because the project seems to me to be a very good idea for NPOs or non-profit organisations and firebase is paid for after 1 gb of space that they provide, so having a local database would solve this problem.

**Comment by remjx** [comment]
I don't expect the database to grow very large. Each Coindrop only takes up 1-2KB of space.

**Comment by remjx** [comment]
Closing this since I don't see any benefit of this for the foreseeable future. Thanks
