### ISSUE TITLE
Payment method request: Nano

### ISSUE THREAD

**Issue by angristan** [remjx/coindrop#366]
Payment method name: Nano

Payment method website: None (cryptocurrency), but the website is https://nano.org/

Link to icon in .SVG format (if available): https://content.nano.org/Nano-Brand-Kit/SVG/nano+circle.svg, as found on https://nano.org/resources

**Comment by remjx** [comment]
Got it, I'll add these within the next couple days.

**Comment by remjx** [comment]
Added.
