### ISSUE TITLE
UPI QR code doesn't work!

### ISSUE THREAD

**Issue by realKarthikNair** [remjx/coindrop#600]
UPI QR code doesn't work

![Screenshot_2022-02-01-03-04-17-80_e4c1cb095b567267d5d1f8fb96ab0b79](https://user-images.githubusercontent.com/78267371/151876930-e43f2eb5-bb80-4e87-a845-af84bc742070.jpg)

**Comment by realKarthikNair** [comment]
Never mind figured out the issue... Actually one should put their UPI link instead of their UPI id

**Comment by TecnikOfficial** [comment]
did upi qr code generated by coindrop works ? its only working when i scan it using gpay . when i use other app it doesnt detect
