### ISSUE TITLE
New payment method request + support in Greek language 

### ISSUE THREAD

**Issue by blinkdreamer** [remjx/coindrop#735]
Payment method name: Stripe

Payment method website: https://stripe.com/en-gr

Link to icon in .SVG format (if available):  

Great work! Thanks a lot in advance!

**Comment by veesar** [comment]
I believe this has been attempted, but Stripe didn't allow it. See: #145

**Comment by remjx** [comment]
> I believe this has been attempted, but Stripe didn't allow it. See: #145

Thanks @veesar you are correct
