### ISSUE TITLE
Unable to sign up

### ISSUE THREAD

**Issue by MagicLike** [remjx/coindrop#795]
**Describe the bug**
I am unable to sign up with my E-mail adress.

**To Reproduce**
1. Click on "Log in / Sign up"
2. Click on "Sign in with email"
3. Enter E-mail adress
4. Click "Next"
5. Open link in E-Mail
6. Get redirected back to coindrop.to
7. Try to login
8. Looping back into the sign up process

**Expected behavior**
That I am able to sign up

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 105.0b9

**Comment by faloi** [comment]
I'm getting almost the same misbehavior when trying to login. 
One thing I noticed is the email I receive points to https://coindropto.firebaseapp.com/ instead of coindrop.to. When the redirection is made on the browser, the login dialog pops up again - and I'm trapped on the loop. 😢

**Comment by GiantCharmer** [comment]
*Experiencing the same loop, with regards to the email sign-up process. (With a further note: The email containing said auth link landed into my spam folder.)

**Comment by remjx** [comment]
Ok I'll check it out.

**Comment by remjx** [comment]
Email login is fixed. Sorry for the inconvenience!

**Comment by GiantCharmer** [comment]
No worries at all, Mark! (I had since switched to the Google login option.)


I do appreciate the response on this issue, however. Cheers, mate! 😎
