### ISSUE TITLE
Cypress test "Creates Coindrop if Create button is pressed and user logs in" (on landing page) is flaky

### ISSUE THREAD

**Issue by remjx** [remjx/coindrop#89]
`AssertionError: Timed out retrying: Expected to find content: 'test-coindrop-tid-lr9rzm' but never did.`

https://github.com/markjackson02/coindrop/blob/master/cypress/integration/landing-page/landing-page.ts#L41

Failing in CI intermittently but always passes when run locally

**Comment by markjackson02** [comment]
Working branch/PR https://github.com/markjackson02/coindrop/pull/90

**Comment by remjx** [comment]
Looks like `cy.reload()` is a sufficient workaround. The firestore XHR requests are like a black box. Yuck.

Keeping this open for now to see if the issue returns in some form (as it has previously).

**Comment by remjx** [comment]
fixed
